CC = gcc
CFLAGS = -g -Wall -m32
EXEC = Tema3

build:
	$(CC) $(CFLAGS) bmp_header.h tema3.c -o Tema3
	./$(EXEC)

run_task1: 
	$(CC) $(CFLAGS) bmp_header.h tema3.c -o Tema3
	./$(EXEC) 1

run_task2:
	$(CC) $(CFLAGS) bmp_header.h tema3.c -o Tema3
	./$(EXEC) 2

run_task3:
	$(CC) $(CFLAGS) bmp_header.h tema3.c -o Tema3
	./$(EXEC) 3

run_task4:
	$(CC) $(CFLAGS) bmp_header.h tema3.c -o Tema3
	./$(EXEC) 4

run_task5:
	$(CC) $(CFLAGS) bmp_header.h tema3.c -o Tema3
	./$(EXEC) 5

run_bonus:
	$(CC) $(CFLAGS) bmp_header.h tema3.c -o Tema3
	./$(EXEC) B


clean:
	-rm -f $(EXEC)
